version: '3.1'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
      - /home/eliezer/:/mnt/eliezer/
    environment:
      NEO4J_AUTH: neo4j/secret
      NEO4J_dbms_logs_debug_level: DEBUG